[package]
name = "compiler-bau"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
rustyline = "15.0.0"
colored = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
clap = "3.2.25"
ctrlc = "3.4.5"
